---
- name: Check parameters
  assert:
    that:
      - spark_worker_home is defined
      - spark_worker_masters is defined

- name: Create working directory on node
  file:
    path: "{{ spark_worker_working_dir }}"
    state: directory
    owner: spark
    group: spark
  tags:
    - spark
    - slaves

- name: Make log directory on node
  file:
    path: "{{ spark_worker_home }}/logs"
    state: directory
    owner: spark
    group: spark
  tags: spark-node

- name: install worker service
  template: src=spark-worker-systemd.j2 dest=/etc/systemd/system/spark-worker.service owner=root group=root mode=755
  tags:
    - spark
    - slaves
  register: tmp_service

- name: reload services
  command: systemctl daemon-reload
  tags:
    - spark
  when: tmp_service.changed

- name: restart worker service
  service: name=spark-worker state=restarted
  tags:
    - spark
    - slave
  when: tmp_service.changed

- name: start worker service
  service: name=spark-worker state=started
  tags:
    - spark
    - slave
