---
- hosts: aws_region_ireland
  roles:
    - network_aws
    - { role: routing_aws, network_id: "{{ network_aws.output.network_id }}" }
    - { role: subnets_aws, network_id: "{{ network_aws.output.network_id }}", routing_ids: "{{ routing_aws.output.routing_ids }}" }


- hosts: aws_nat_1
  roles:
    - { role: nat_aws, network_id: "{{ hostvars.aws_region_ireland.network_aws.output.network_id }}", subnet_id: "{{ hostvars.aws_region_ireland.subnets_aws.output.subnet_ids.public }}", routing_ids: "{{ { 'private': hostvars.aws_region_ireland.routing_aws.output.routing_ids.private } }}"}

- hosts: aws_datalake_1
  roles:
    - { role: datalake_aws, network_id: "{{ hostvars.aws_region_ireland.network_aws.output.network_id }}", subnet_id: "{{ hostvars.aws_region_ireland.subnets_aws.output.subnet_ids.private }}"}
