---


- name: Check required parameters (general)
  assert:
    that:
      - "routing is defined"

- name: Check required parameters (all entries should have ID)
  assert:
    that:
      - "item.value.id is defined" # Clients of the routing module require the ID of the routing table.
  with_dict: routing
  when: route is undefined

- name: "Check required parameters (check specific entry for ID: {{ route }})"
  assert:
    that:
      - "routing[route].id is defined"
  when: route is defined


