---


- name: "Check required parameters (multiple routing tables: routing_ids)"
  assert:
    that:
      - "routing_ids is defined"
  when: multi

- name: "Check required parameters (single routing table: routing_id)"
  assert:
    that:
      - "routing_id is defined"
  when: not multi

