---

# We use the external docker API made available to us to provision this
- name: Check parameters
  assert:
    that:
      - docker_client_cert is defined
      - docker_client_key is defined
      - docker_client_cacert is defined
      - docker_endpoint is defined

- set_fact:
    docker_cmd: docker --tlsverify --tlscacert={{ docker_client_cacert }} --tlscert={{ docker_client_cert }} --tlskey={{ docker_client_key }} -H {{ docker_endpoint }}

- name: Check for Gateway Network
  command: |
    {{ docker_cmd }}
    network inspect gateway
  register: tmp_command_result
  failed_when: "'Usage' in tmp_command_result.stderr"

- set_fact:
    tmp_network_exists: "{{ tmp_command_result.stderr == ''}}"


- name: Deploy Gateway Network
  command: |
    {{ docker_cmd }}
    network create --driver overlay gateway
  when: not tmp_network_exists


- name: Check for Swarm Listener Service
  command: |
    {{ docker_cmd }}
    service inspect swarm-listener
  register: tmp_command_result
  failed_when: "'Usage' in tmp_command_result.stderr"

- set_fact:
    tmp_service_exists: "{{ tmp_command_result.stderr == ''}}"

- name: Deploy Swarm Listener Service
  command: |
    {{ docker_cmd }}
    service create --name swarm-listener
    --network gateway
    --constraint 'node.role==manager'
    --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock"
    -e DF_NOTIFY_CREATE_SERVICE_URL=http://gateway:8080/v1/docker-flow-proxy/reconfigure
    -e DF_NOTIFY_REMOVE_SERVICE_URL=http://gateway:8080/v1/docker-flow-proxy/remove
    vfarcic/docker-flow-swarm-listener
  when: not tmp_service_exists

- name: Check for Gateway Service
  command: |
    {{ docker_cmd }}
    service inspect gateway
  register: tmp_command_result
  failed_when: "'Usage' in tmp_command_result.stderr"

- set_fact:
    tmp_service_exists: "{{ tmp_command_result.stderr == ''}}"

- name: Deploy Gateway Service
  command: |
    {{ docker_cmd }}
    service create --name gateway
    --mode global
    --network gateway
    -p 80:80
    -p 443:443
    -e MODE=swarm
    -e LISTENER_ADDRESS=swarm-listener
    vfarcic/docker-flow-proxy
  when: not tmp_service_exists










