---
- assert:
    that:
      - "datalake is defined"
      - "datalake.release is defined"
      - "datalake.name is defined"
      - "datalake.applications is defined"
      - "datalake.instance_groups is defined"
      - "datalake.instance_groups.master is defined"
      - "datalake.instance_groups.worker is defined"
      - "datalake.key_pair is defined"
      - "datalake.subnet is defined"

- assert:
    that:
      - "item.value.count is defined" # Instance master/worker should have a name.
      - "item.value.type is defined" # Instance master/worker should have a type.
  with_dict: datalake.instance_groups
