---



- name: "Check required parameters (multiple subnets: subnet_ids)"
  assert:
    that:
      - "subnet_ids is defined"
  when: multi

- name: "Check required parameters (single subnet: subnet_id)"
  assert:
    that:
      - "subnet_id is defined"
  when: not multi




