---
- name: Check required parameters (stack, network name, and CIDR)
  assert:
    that:
      - "stack is defined"
      - "network is defined"
      - "network.name is defined"
      - "network.cidr is defined"
