---

- name: Check parameters (1/2)
  assert:
    that: repositories is defined

- name: Check parameters (2/2)
  assert:
    that:
      - item.value.url is defined or item.value.local is defined
  with_dict: "{{ repositories }}"


- name: Install external repository files
  get_url:
    url:  "{{ item.value.url }}"
    dest: "/etc/yum.repos.d/{{item.key}}.repo"
    mode: 0644
  with_dict: "{{ repositories }}"
  when: item.value.url is defined

- name: Install provided repository files
  copy:
    src:  "{{ item.value.local }}"
    dest: "/etc/yum.repos.d/{{item.key}}.repo"
    mode: 0644
  with_dict: "{{ repositories }}"
  when: item.value.local is defined

- name: Install provided gpg keys
  copy:
    src:  "{{ item.value.key }}"
    dest: "/etc/pki/rpm-gpg/{{item.key}}"
    mode: 0644
  with_dict: "{{ repositories }}"
  when: item.value.key is defined

