---

- name: Check parameters
  assert:
    that:
      - anaconda_install_dir is defined

- name: Install jupyter single user service
  template: src=jupyter.service.j2 dest=/lib/systemd/system/jupyter.service mode=0644
  notify:
    - daemon_reload
    - restart_jupyter

