---
- name: Check required parameters (general)
  assert:
    that:
      - "routing is defined"

- name: Check required parameters (routing table names)
  assert:
    that:
      - "item.value.name is defined" # Routing table should have a name.
  with_dict: routing
