Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false



  config.vm.define "bdr-container-node-3", autostart: true do |vm|
      vm.vm.hostname = "bdr-container-node-3"
      vm.vm.network "private_network", ip: "10.0.0.47"

      # Provision virtualbox:
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = 2048 # 2 GB
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
      end
  end

  config.vm.define "bdr-container-node-2", autostart: true do |vm|
      vm.vm.hostname = "bdr-container-node-2"
      vm.vm.network "private_network", ip: "10.0.0.46"

      # Provision virtualbox:
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = 2048 # 2 GB
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
      end
  end

  config.vm.define "bdr-container-node-1", autostart: true do |vm|
      vm.vm.hostname = "bdr-container-node-1"
      vm.vm.network "private_network", ip: "10.0.0.45"
      vm.vm.synced_folder "../", "/vagrant"

      vm.vm.provision :shell, path: "vagrant.sh", run: "always"
      vm.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "provision.yml"
        ansible.inventory_path = "example-inventory/dev"
        ansible.provisioning_path = "/vagrant/embedded-execution-layer"
        ansible.raw_arguments = ['-u vagrant']
        ansible.limit = "all" # or only "nodes" group, etc.
      end

      vm.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "flow-proxy.yml"
        ansible.inventory_path = "example-inventory/dev"
        ansible.provisioning_path = "/vagrant/embedded-execution-layer"
        ansible.raw_arguments = ['-u vagrant']
        ansible.limit = "all" # or only "nodes" group, etc.
      end

      # Provision virtualbox:
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = 2048 # 2 GB
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
      end
  end


end
