---

- name: Generate subnets/ACL template
  template: src="subnets.json.j2" dest="{{ tmp_dir }}/subnets.json"

- name: Create subnets and nACLs
  cloudformation:
    stack_name: "{{ stack }}-subnets"
    state: "present"
    region: "{{ aws_region }}"
    disable_rollback: true
    template: "{{ tmp_dir }}/subnets.json"
    tags:
      stack: "{{ stack }}"
