---

nat:
  id: 1
  name: "{{ stack }} - NAT"
  type: t2.micro
  key_pair: "{{stack}}"
  firewall:
    nat:
      inbound:
        tcp:
          - "0-65535": master
          - "0-65535": worker
      outbound: {}
