---

datalake:
  id: 1
  release: "emr-4.7.2"
  name: "EMR Cluster"
  applications:
    - Spark
    - Hadoop
    - Hive
  key_pair: "{{ stack }}"
  instance_groups:
    master:
      count: 1
      type: m4.large
      market: 0.264
    worker:
      count: 2
      type: m4.large
      market: 0.264
  firewall:
    master:
      instance_group: master # References "master" in instance_groups. Cannot reference like this outside the datalake.instance_groups.
      inbound:
        tcp:
          - "0-65535": master # References "master" in firewall. Cannot reference like this outside the datalake.firewall unless provided in firewall_ids.
          - "0-65535": worker
          - "8443": service
        icmp:
          - "0-65535": master
          - "0-65535": worker
        udp:
          - "0-65535": master
          - "0-65535": worker
      outbound: {}
    worker:
      instance_group: worker
      inbound:
        tcp:
          - "0-65535": master
          - "0-65535": worker
          - "8443": service
        icmp:
          - "0-65535": master
          - "0-65535": worker
        udp:
          - "0-65535": master
          - "0-65535": worker
      outbound: {}
    service:
      inbound: {}
      outbound:
        tcp:
          - "8443": master
          - "8443": worker
