---

- name: Generate subnets/ACL template
  template: src="subnets.json.j2" dest="{{ tmp_dir }}/subnets.json"

- name: Create subnets and nACLs
  cloudformation:
    stack_name: "{{ stack }}-subnets"
    state: "present"
    region: "{{ aws_region }}"
    disable_rollback: true
    template: "{{ tmp_dir }}/subnets.json"
    tags:
      stack: "{{ stack }}"
  register: subnets_aws_stack

- name: Show stack outputs
  debug: msg="My stack outputs are {{subnets_aws_stack.stack_outputs}}"


- name: Define Outputs
  set_fact:
    subnets_aws: "{{ {'output': {'subnet_ids': subnets_aws_stack.stack_outputs}} }}"

